// design/components/TenantManagementModal.tsx
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from './ui/dialog';
import { Button } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Avatar, AvatarImage, AvatarFallback } from './ui/avatar';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { User, Shield, Building, Users, Check, X } from 'lucide-react';
import { Tenant, User as UserType, Application } from '../App';
import { toast } from 'sonner@2.0.3';

interface TenantManagementModalProps {
  isOpen: boolean;
  onClose: () => void;
  tenant: Tenant;
  users: UserType[];
  applications: Application[];
  onAssignTenantAdmin: (tenantId: string, userId: string) => void;
}

const TenantManagementModal = ({ 
  isOpen, 
  onClose, 
  tenant, 
  users = [], 
  applications = [],
  onAssignTenantAdmin 
}: TenantManagementModalProps) => {
  const [selectedAdminId, setSelectedAdminId] = useState<string>('');
  const [isAssigning, setIsAssigning] = useState(false);

  // Get available users who can be tenant admins (not already assigned to other tenants)
  const availableAdmins = users.filter(user => 
    (user.role === 'platform_tenant_admin' && !user.tenantId) ||
    (user.role === 'platform_user' && !user.tenantId)
  );

  const currentTenantAdmin = users.find(user => user.id === tenant.tenantAdminId);
  const tenantUsers = users.filter(user => user.tenantId === tenant.id);

  const handleAssignAdmin = async () => {
    if (!selectedAdminId) return;
    
    setIsAssigning(true);
    
    // Simulate API call
    setTimeout(() => {
      onAssignTenantAdmin(tenant.id, selectedAdminId);
      toast.success('Tenant admin assigned successfully!');
      setIsAssigning(false);
      setSelectedAdminId('');
      onClose();
    }, 1000);
  };

  const getTotalMonthlyCost = () => {
    return (tenant.subscribedApplications || []).reduce((total, appId) => {
      const app = applications.find(a => a.id === appId);
      return total + (app?.monthlyPrice || 0);
    }, 0);
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center space-x-2">
            <Building className="h-5 w-5 text-blue-600" />
            <span>Manage {tenant.name}</span>
          </DialogTitle>
          <DialogDescription>
            Configure tenant settings, assign administrators, and manage subscriptions
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Tenant Overview */}
          <Card>
            <CardHeader>
              <CardTitle className="text-foreground">Tenant Overview</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div>
                  <p className="text-sm text-muted-foreground">Organization</p>
                  <p className="font-medium text-foreground">{tenant.name}</p>
                  <p className="text-xs text-muted-foreground">{tenant.type} • {tenant.industry}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Status</p>
                  <Badge variant={tenant.status === 'active' ? 'default' : 'secondary'}>
                    {tenant.status}
                  </Badge>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Monthly Revenue</p>
                  <p className="font-medium text-foreground">${getTotalMonthlyCost()}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">User Limit</p>
                  <p className="font-medium text-foreground">{tenant.userLimit}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Compliance</p>
                  <p className="font-medium text-foreground">{tenant.complianceLevel}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Created</p>
                  <p className="font-medium text-foreground">{tenant.createdAt}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Subscribed Applications */}
          <Card>
            <CardHeader>
              <CardTitle className="text-foreground">Subscribed Applications</CardTitle>
              <CardDescription>Applications available to this tenant</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {(tenant.subscribedApplications || []).map(appId => {
                  const app = applications.find(a => a.id === appId);
                  if (!app) return null;
                  
                  return (
                    <div key={app.id} className="flex items-center justify-between p-3 bg-muted/30 rounded-lg">
                      <div className="flex items-center space-x-3">
                        <div className={`h-8 w-8 rounded-lg flex items-center justify-center ${
                          app.isHighlighted ? 'bg-blue-600 text-white' : 'bg-muted text-muted-foreground'
                        }`}>
                          <Shield className="h-4 w-4" />
                        </div>
                        <div>
                          <p className="font-medium text-foreground">{app.name}</p>
                          <p className="text-xs text-muted-foreground">{app.description}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="font-medium text-foreground">${app.monthlyPrice}/mo</p>
                        {app.isHighlighted && (
                          <Badge variant="outline" className="border-yellow-400 text-yellow-600 text-xs">
                            Featured
                          </Badge>
                        )}
                      </div>
                    </div>
                  );
                })}
                {(!tenant.subscribedApplications || tenant.subscribedApplications.length === 0) && (
                  <div className="col-span-full text-center py-4">
                    <p className="text-muted-foreground">No applications subscribed</p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Tenant Admin Assignment */}
          <Card>
            <CardHeader>
              <CardTitle className="text-foreground">Tenant Administrator</CardTitle>
              <CardDescription>
                Assign a tenant administrator who will manage users and applications for this organization
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {currentTenantAdmin ? (
                <div className="flex items-center justify-between p-4 bg-green-50 border border-green-200 rounded-lg">
                  <div className="flex items-center space-x-3">
                    <div className="h-10 w-10 rounded-full bg-green-600/10 flex items-center justify-center">
                      <User className="h-5 w-5 text-green-600" />
                    </div>
                    <div>
                      <p className="font-medium text-foreground">{currentTenantAdmin.name}</p>
                      <p className="text-sm text-muted-foreground">{currentTenantAdmin.email}</p>
                      <Badge variant="outline" className="border-green-500 text-green-600 text-xs mt-1">
                        Current Admin
                      </Badge>
                    </div>
                  </div>
                  <Check className="h-5 w-5 text-green-600" />
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="flex items-center space-x-3 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                    <Shield className="h-5 w-5 text-yellow-600" />
                    <div>
                      <p className="font-medium text-foreground">No Administrator Assigned</p>
                      <p className="text-sm text-muted-foreground">This tenant needs an administrator to manage users and applications</p>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <div>
                      <label className="text-sm font-medium text-foreground">Select Administrator</label>
                      <Select value={selectedAdminId} onValueChange={setSelectedAdminId}>
                        <SelectTrigger className="mt-1">
                          <SelectValue placeholder="Choose a user to assign as tenant admin" />
                        </SelectTrigger>
                        <SelectContent>
                          {availableAdmins.map(user => (
                            <SelectItem key={user.id} value={user.id}>
                              <div className="flex items-center space-x-2">
                                <span>{user.name}</span>
                                <span className="text-muted-foreground">({user.email})</span>
                                <Badge variant="outline" className="text-xs">
                                  {user.role === 'platform_tenant_admin' ? 'Tenant Admin' : 'User'}
                                </Badge>
                              </div>
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <Button 
                      onClick={handleAssignAdmin}
                      disabled={!selectedAdminId || isAssigning}
                      className="bg-blue-600 hover:bg-blue-700"
                    >
                      {isAssigning ? (
                        <>
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                          Assigning...
                        </>
                      ) : (
                        <>
                          <Shield className="h-4 w-4 mr-2" />
                          Assign as Tenant Admin
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Tenant Users */}
          <Card>
            <CardHeader>
              <CardTitle className="text-foreground">Tenant Users</CardTitle>
              <CardDescription>
                Users belonging to this tenant organization
              </CardDescription>
            </CardHeader>
            <CardContent>
              {tenantUsers.length > 0 ? (
                <div className="space-y-3">
                  {tenantUsers.map(user => (
                    <div key={user.id} className="flex items-center justify-between p-3 bg-muted/30 rounded-lg">
                      <div className="flex items-center space-x-3">
                        <div className="h-8 w-8 rounded-full bg-blue-600/10 flex items-center justify-center">
                          <User className="h-4 w-4 text-blue-600" />
                        </div>
                        <div>
                          <p className="font-medium text-foreground">{user.name}</p>
                          <p className="text-sm text-muted-foreground">{user.email}</p>
                        </div>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge variant={user.role === 'platform_tenant_admin' ? 'default' : 'secondary'}>
                          {user.role === 'platform_tenant_admin' ? 'Admin' : 'User'}
                        </Badge>
                        {user.assignedApplications && user.assignedApplications.length > 0 && (
                          <Badge variant="outline" className="text-xs">
                            {user.assignedApplications.length} Apps
                          </Badge>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8">
                  <Users className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                  <p className="text-muted-foreground">No users assigned to this tenant yet</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        <div className="flex justify-end space-x-2 pt-4">
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default TenantManagementModal;

// frontend/hub/src/app/components/tenant-management-modal/tenant-management-modal.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

interface Tenant {
  id: string;
  name: string;
  type: string;
  industry: string;
  status: string;
  users: any[];
  monthlyRevenue: number;
  tenantAdminId?: string;
  subscribedApplications: string[];
}

interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  tenantId?: string | null;
  assignedApplications?: string[];
}

interface Application {
  id: string;
  name: string;
  description: string;
  icon: string;
  monthlyPrice: number;
  features: string[];
}

@Component({
  selector: 'app-tenant-management-modal',
  templateUrl: './tenant-management-modal.component.html',
  styleUrls: ['./tenant-management-modal.component.css'],
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule]
})
export class TenantManagementModalComponent implements OnChanges {
  @Input() isOpen = false;
  @Input() tenant: Tenant | null = null;
  @Input() users: User[] = [];
  @Input() applications: Application[] = [];
  @Output() onClose = new EventEmitter<void>();
  @Output() onAssignTenantAdmin = new EventEmitter<{tenantId: string, userId: string}>();

  tenantForm: FormGroup;
  isLoading = false;

  constructor(private fb: FormBuilder) {
    this.tenantForm = this.fb.group({
      name: ['', Validators.required],
      type: ['', Validators.required],
      industry: ['', Validators.required],
      status: ['', Validators.required],
      tenantAdminId: [''],
      subscribedApplications: [[]]
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    console.log('ngOnChanges called:', changes);
    if (changes['tenant'] && this.tenant) {
      console.log('Populating form with tenant data:', this.tenant);
      this.tenantForm.patchValue({
        name: this.tenant.name,
        type: this.tenant.type,
        industry: this.tenant.industry,
        status: this.tenant.status,
        tenantAdminId: this.tenant.tenantAdminId || '',
        subscribedApplications: this.tenant.subscribedApplications || []
      });
      console.log('Form populated successfully');
    }
  }

  handleClose() {
    this.onClose.emit();
  }

  handleAssignAdmin() {
    const tenantAdminId = this.tenantForm.get('tenantAdminId')?.value;
    if (tenantAdminId && this.tenant) {
      this.isLoading = true;
      
      // Simulate API call
      setTimeout(() => {
        this.onAssignTenantAdmin.emit({
          tenantId: this.tenant!.id,
          userId: tenantAdminId
        });
        this.isLoading = false;
        alert('Tenant admin assigned successfully!');
      }, 1000);
    }
  }

  handleSaveChanges() {
    if (this.tenantForm.valid) {
      this.isLoading = true;
      
      // Simulate API call to save tenant changes
      setTimeout(() => {
        // Here you would typically make an API call to save the tenant data
        console.log('Saving tenant changes:', this.tenantForm.value);
        
        this.isLoading = false;
        alert('Tenant changes saved successfully!');
        
        // Close the modal after successful save
        this.handleClose();
      }, 1000);
    } else {
      // Mark all fields as touched to show validation errors
      Object.keys(this.tenantForm.controls).forEach(key => {
        const control = this.tenantForm.get(key);
        control?.markAsTouched();
      });
    }
  }

  handleApplicationToggle(appId: string) {
    const currentApps = this.tenantForm.get('subscribedApplications')?.value || [];
    const index = currentApps.indexOf(appId);
    
    if (index > -1) {
      currentApps.splice(index, 1);
    } else {
      currentApps.push(appId);
    }
    
    this.tenantForm.patchValue({ subscribedApplications: currentApps });
  }

  getApplicationName(appId: string): string {
    const app = this.applications.find(a => a.id === appId);
    return app?.name || appId;
  }

  getApplicationPrice(appId: string): number {
    const app = this.applications.find(a => a.id === appId);
    return app?.monthlyPrice || 0;
  }

  getTotalMonthlyCost(): number {
    const selectedApps = this.tenantForm.get('subscribedApplications')?.value || [];
    return selectedApps.reduce((total: number, appId: string) => {
      const app = this.applications.find(a => a.id === appId);
      return total + (app?.monthlyPrice || 0);
    }, 0);
  }

  getAvailableUsers(): User[] {
    return this.users.filter(user => 
      (user.role === 'platform_tenant_admin' || user.role === 'platform_user') && 
      (!user.tenantId || user.tenantId === this.tenant?.id)
    );
  }

  getCurrentTenantAdmin(): User | undefined {
    if (!this.tenant?.tenantAdminId) return undefined;
    return this.users.find(u => u.id === this.tenant?.tenantAdminId);
  }

  getRoleDisplayName(role: string): string {
    switch (role) {
      case 'platform_tenant_admin': return 'Tenant Admin';
      case 'platform_user': return 'User';
      case 'platform_admin': return 'Platform Admin';
      default: return role.replace('platform_', '').replace('_', ' ');
    }
  }
} 
<div *ngIf="isOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
  <div class="bg-background rounded-xl shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
    <!-- Header -->
    <div class="flex items-center justify-between p-6 border-b border-border">
      <div>
        <h2 class="text-2xl font-bold text-foreground">Manage Tenant</h2>
        <p class="text-muted-foreground">Configure tenant settings and assignments</p>
      </div>
      <button 
        (click)="handleClose()"
        class="text-muted-foreground hover:text-foreground p-2 rounded-md hover:bg-accent"
      >
        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>

    <!-- Content -->
    <div class="p-6">
      <form [formGroup]="tenantForm" class="space-y-6">
        <!-- Basic Information -->
        <div class="bg-card border border-border rounded-xl p-6">
          <h3 class="text-lg font-semibold text-foreground mb-4">Basic Information</h3>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="block text-sm font-medium text-foreground mb-2">Organization Name</label>
              <input type="text" formControlName="name" 
                     class="w-full px-3 py-2 border border-border rounded-md bg-background text-foreground"
                     placeholder="Enter organization name">
            </div>
            
            <div>
              <label class="block text-sm font-medium text-foreground mb-2">Organization Type</label>
              <select formControlName="type" 
                      class="w-full px-3 py-2 border border-border rounded-md bg-background text-foreground">
                <option value="">Select type</option>
                <option value="Enterprise">Enterprise</option>
                <option value="Professional">Professional</option>
                <option value="Standard">Standard</option>
                <option value="Starter">Starter</option>
              </select>
            </div>
            
            <div>
              <label class="block text-sm font-medium text-foreground mb-2">Industry</label>
              <select formControlName="industry" 
                      class="w-full px-3 py-2 border border-border rounded-md bg-background text-foreground">
                <option value="">Select industry</option>
                <option value="Technology">Technology</option>
                <option value="Finance">Finance</option>
                <option value="Healthcare">Healthcare</option>
                <option value="Legal">Legal</option>
                <option value="Retail">Retail</option>
                <option value="Manufacturing">Manufacturing</option>
              </select>
            </div>
            
            <div>
              <label class="block text-sm font-medium text-foreground mb-2">Status</label>
              <select formControlName="status" 
                      class="w-full px-3 py-2 border border-border rounded-md bg-background text-foreground">
                <option value="">Select status</option>
                <option value="active">Active</option>
                <option value="suspended">Suspended</option>
                <option value="pending">Pending</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Tenant Admin Assignment -->
        <div class="bg-card border border-border rounded-xl p-6">
          <h3 class="text-lg font-semibold text-foreground mb-4">Tenant Administrator</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-foreground mb-2">Assign Tenant Admin</label>
              <select formControlName="tenantAdminId" 
                      class="w-full px-3 py-2 border border-border rounded-md bg-background text-foreground">
                <option value="">Choose a user to assign as tenant admin</option>
                <option *ngFor="let user of getAvailableUsers()" [value]="user.id">
                  {{ user.name }} ({{ user.email }}) - {{ getRoleDisplayName(user.role) }}
                </option>
              </select>
            </div>
            
            <div *ngIf="getCurrentTenantAdmin()" class="p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p class="text-sm text-blue-800">
                <strong>Current Admin:</strong> {{ getCurrentTenantAdmin()?.name }} ({{ getCurrentTenantAdmin()?.email }})
              </p>
            </div>
            
            <button 
              type="button"
              (click)="handleAssignAdmin()"
              [disabled]="!tenantForm.get('tenantAdminId')?.value || isLoading"
              class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <svg *ngIf="isLoading" class="animate-spin -ml-1 mr-2 h-4 w-4 text-white inline" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              {{ isLoading ? 'Assigning...' : 'Assign Admin' }}
            </button>
          </div>
        </div>

        <!-- Application Management -->
        <div class="bg-card border border-border rounded-xl p-6">
          <h3 class="text-lg font-semibold text-foreground mb-4">Subscribed Applications</h3>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div *ngFor="let app of applications" 
                 class="p-4 border border-border rounded-lg cursor-pointer transition-colors"
                 [class]="(tenantForm.get('subscribedApplications')?.value || []).includes(app.id) 
                   ? 'border-blue-500 bg-blue-50' : 'hover:bg-accent'"
                 (click)="handleApplicationToggle(app.id)">
              <div class="flex items-center justify-between mb-2">
                <div class="flex items-center space-x-2">
                  <div class="h-8 w-8 rounded-lg bg-blue-600 text-white flex items-center justify-center">
                    <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>
                    </svg>
                  </div>
                  <span class="font-medium text-foreground">{{ app.name }}</span>
                </div>
                <span class="text-sm font-medium text-foreground">${{ app.monthlyPrice }}/month</span>
              </div>
              <p class="text-sm text-muted-foreground">{{ app.description }}</p>
              <div class="flex flex-wrap gap-1 mt-2">
                <span *ngFor="let feature of app.features.slice(0, 2)" 
                      class="text-xs bg-muted text-muted-foreground px-2 py-1 rounded">
                  {{ feature }}
                </span>
              </div>
            </div>
          </div>
          
          <div *ngIf="getTotalMonthlyCost() > 0" class="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
            <div class="flex items-center justify-between">
              <span class="font-medium text-blue-800">Total Monthly Cost:</span>
              <span class="font-bold text-blue-800">${{ getTotalMonthlyCost() }}/month</span>
            </div>
          </div>
        </div>

        <!-- Tenant Statistics -->
        <div class="bg-card border border-border rounded-xl p-6">
          <h3 class="text-lg font-semibold text-foreground mb-4">Tenant Statistics</h3>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div class="p-4 bg-muted/30 rounded-lg">
              <p class="text-sm text-muted-foreground">Total Users</p>
              <p class="text-2xl font-bold text-foreground">{{ tenant?.users?.length || 0 }}</p>
            </div>
            <div class="p-4 bg-muted/30 rounded-lg">
              <p class="text-sm text-muted-foreground">Monthly Revenue</p>
              <p class="text-2xl font-bold text-foreground">${{ tenant?.monthlyRevenue || 0 }}</p>
            </div>
            <div class="p-4 bg-muted/30 rounded-lg">
              <p class="text-sm text-muted-foreground">Subscribed Apps</p>
              <p class="text-2xl font-bold text-foreground">{{ tenant?.subscribedApplications?.length || 0 }}</p>
            </div>
          </div>
        </div>
      </form>
    </div>

    <!-- Footer -->
    <div class="flex items-center justify-end space-x-3 p-6 border-t border-border">
      <button 
        (click)="handleClose()"
        class="px-4 py-2 border border-border bg-background text-foreground rounded-md hover:bg-accent"
      >
        Close
      </button>
      <button 
        type="button"
        (click)="handleSaveChanges()"
        [disabled]="isLoading"
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        <svg *ngIf="isLoading" class="animate-spin -ml-1 mr-2 h-4 w-4 text-white inline" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        {{ isLoading ? 'Saving...' : 'Save Changes' }}
      </button>
    </div>
  </div>
</div>
